### ISSUE TITLE
Fastboot?

### ISSUE THREAD

**Issue by evoactivity** [ember-vr/ember-aframe#46]
I'm building an app that supports fastboot and one area of the app is a VR experience using this addon. Problem is just importing aframe knocks over fastboot, I'm not expecting the scene to render in fastboot.

What could be done to make the Aframe import conditional on the environment?

**Comment by kellyselden** [comment]
I'm not sure. We can look at how some other addons guard against fastboot. We could start with adding a failing fastboot test using ember-cli-addon-tests (or ember-fastboot-addon-tests).
