### ISSUE TITLE
Cursor not working on Samsung Gear VR

### ISSUE THREAD

**Issue by hybridmuse** [ember-vr/ember-aframe#52]
I've been playing with ember-aframe on my computer and I must say that I'm really enjoying this!
Unfortunately, testing the app on Samsung Gear VR (my only VR device) shows that it's not compatible with it (cursor isn't working).

I believe this is the solution:
https://github.com/chenzlabs/gearvr-controls

Do you think it could, by any chance, be integrated into your work?
Thanks a lot for your time!

**Comment by hybridmuse** [comment]
Hi,
Can you at least tell me which VR headset you're using for testing this?
Thanks

**Comment by kellyselden** [comment]
I used google cardboard for testing.

**Comment by kellyselden** [comment]
I just released a new version targetting latest Aframe. Please try now.
