### ISSUE TITLE
Document what's needed to update/build this

### ISSUE THREAD

**Issue by gabrielgrant** [ember-vr/ember-aframe#79]
I'd like to test this with the newly-updated version of ember-aframe-shim. Is it just a matter of upping the dependency, or is there more of a build-step needed? (I gather this repo is doing some sort of code generation to avoid copying over A-frame components, but I'm not totally sure how it works)

(also, sorry for nagging you about getting these updates plumbed through. happy to do the legwork if there are other changed needed here)

**Comment by kellyselden** [comment]
just updating the dep should be enough.

**Comment by kellyselden** [comment]
Don't think this applies anymore.
